### ISSUE TITLE
CSS Styling for Room selection page.  

### ISSUE THREAD

**Issue by bbeeksma** [dustinyschild/hotel-final-project#8]
Use Style guide for fonts and colors.  Make it pretty.

**Comment by bbeeksma** [comment]
html layout should be using re-usable classes as much as possible. hopefully a lot of this styling will get taken care of as home page is completed

**Comment by thecforsythe** [comment]
established a mvp for the room selection sheet tuesday night
https://github.com/dustinyschild/hotel-final-project/pull/30
